export const categories = [
  { label: "Breaking", value: "Breaking".toLowerCase() },
  { label: "Business", value: "Business".toLowerCase() },
  { label: "Crime", value: "Crime".toLowerCase() },
  { label: "Domestic", value: "Domestic".toLowerCase() },
  { label: "Education", value: "Education".toLowerCase() },
  { label: "Entertainment", value: "Entertainment".toLowerCase() },
  { label: "Environment", value: "Environment".toLowerCase() },
  { label: "Food", value: "Food".toLowerCase() },
  { label: "Health", value: "Health".toLowerCase() },
  { label: "Lifestyle", value: "Lifestyle".toLowerCase() },
  { label: "Politics", value: "Politics".toLowerCase() },
  { label: "Science", value: "Science".toLowerCase() },
  { label: "Sports", value: "Sports".toLowerCase() },
  { label: "Technology", value: "Technology".toLowerCase() },
  { label: "Top", value: "Top".toLowerCase() },
  { label: "Tourism", value: "Tourism".toLowerCase() },
  { label: "World", value: "World".toLowerCase() },
  { label: "Other", value: "Other".toLowerCase() },
];
